Someone check
PrepHQ/PrepHQ_Connect pull request #20
Opened 2020-11-01 22:57 UTC by s-oswald

Something got messed up with my flutter pub get for getting the dependencies. Can someone try to run this on their machine and see if it works? Gotta figure out what the issue is.

2020-11-01 23:07 UTC, IcemanOmikron approved these changes

2020-11-03 21:42 UTC, ggpepp commented
I think it should all work now but test on your systems as well.

2020-11-04 15:09 UTC, chwerth requested changes
This is a massive amount of progress, really great job @s-oswald.

My last random comment is, with the new routing you implemented the android back button is now willing to take you back to the Login Screen if you hit it right after you login. Is there a simple way to pop the login screen off the stack once we login?

2020-11-04 15:09 UTC, chwerth commented on README.md
> +The PrepHQ Connect app
Can we keep the image? I don't know if you did this on purpose.

2020-11-04 15:09 UTC, chwerth commented on lib/views/auth/login.dart
> +class MyHomePage extends StatefulWidget {
Can we name this `LoginScreen`? Makes it a little easier to immediately grasp what the widget is

2020-11-04 15:09 UTC, chwerth commented on lib/views/student/studentscreen.dart
> +      body: IndexedStack(
Out of curiosity, what makes `IndexedStack` a better choice here?

2020-11-05 23:56 UTC, chwerth approved these changes

2020-11-05 23:57 UTC, chwerth commented
@s-oswald I think I made all the changes I needed to, feel free to merge whenever

2020-11-06 14:16 UTC, merged